coverage:
  precision: 2
  round: down
  range: "1...100"
  status:
    patch:
      default:
        target: auto
        threshold: 0%
    project:
      default:
        target: auto
        threshold: 1%
codecov:
  require_ci_to_pass: no
  notify:
    after_n_builds: 1
    wait_for_ci: no
