coverage:
  precision: 2
  round: down
  range: "1...100"
  status:
    patch:
      default:
        target: auto
        threshold: 0%
    project:
      default:
        target: auto
        threshold: 1%
