#!/usr/bin/env bash
#
# Script to interact with IDAES docker image.
#

function usage () {
   printf "./idaes-docker COMMAND\n\n"
   printf "User commands:\n"
   printf "   help          Print this message\n"
   printf "   test          Run the unit tests on the Docker image.\n"
   printf "   notebook      Run a Jupyter notebook inside the Docker image.\n"
   printf "   update        Get the latest version of the IDAES Docker image.\n"
   printf "Developer commands:\n"
   printf "   create         Build new Docker image (creates a .tgz file)\n"
   exit 1
}

# Expected repository and tag of Docker image to use
IMAGE_REPO=idaes
IMAGE_TAG=idaes_pse

# Check if image is present. Ask to install it, if not.
function check_image() {
  n=$(docker images -q ${IMAGE_REPO}:${IMAGE_TAG} | wc -l)
  if [ $n -eq 0 ]; then
    printf "Docker image ${IMAGE_REPO}:${IMAGE_TAG} not found\n"
    printf "Download and install latest image now (y/N)? "
    read response
    case "$response" in
      y|Y|yes|Yes|YES) install_image ;;
      *) install_image_help; exit 1 ;;
    esac
  fi
}

function install_image() {
  url="https://s3.amazonaws.com/idaes/idaes-pse"
  filenm="idaes-pse-docker-latest.tgz"
  wget -h > /dev/null 2>&1
  if [ $? -eq 0 ]; then
    getcmd=wget
  else
    curl -h > /dev/null 2>&1
    if [ $? -eq 0 ]; then
      getcmd="curl -o $filenm"
    else
      printf "Could not find 'curl' or 'wget' command. Abort.\n"
      exit 1
    fi
  fi
  printf "Downloading image..\n"
  $getcmd ${url}/${filenm}
  if [ $? -ne 0 ]; then
    printf "Download failed. Abort command.\n"
    exit 1
  fi
  printf "Loading image..\n"
  docker load < $filenm
}

function install_image_help() {
  printf "Command aborted.\n\nFor information on how to install and use\n"
  printf "Docker with the IDAES PSE framework, see the installation guide at:\n"
  printf "    https://idaes.github.io/idaes-pse/install.html\n"
}

function build_image() {
  ver=$( python -c "from idaes import ver; print(ver.__version__, end='')" )
  printf "Detected IDAES package version $ver\n"
  vertag="${IMAGE_REPO}/${IMAGE_TAG}:v${ver}"
  tagopt="-t ${vertag}"
  # extract user-provided tags
  while [[ $# -gt 0 ]]; do
    tagopt="$tagopt -t ${IMAGE_REPO}/${IMAGE_TAG}:$1"
    shift
  done
  # Build image and saved file, skipping when there seems to already
  # be something built
  imgname=idaes-pse-docker-${ver}.tgz
  if [[ ! -e $imgname ]]; then
    imgid=$( docker images -q $vertag )
    if [[ -z "$imgid" ]]; then
      printf "Building image...\n"
      docker build . $tagopt
      imgid=$( docker images -q $vertag )
    else
      printf "Nothing to do: image $vertag already exists ($imgid)\n"
    fi
    printf "Saving image..\n"
    docker save $imgid | gzip -c >  $imgname
    printf "Done: $imgname \n"
  else
    printf "Nothing to do: image file $imgname already exists\n"
  fi
}

if [[ -z $1 ]]; then
  usage
fi

case $1 in
    test)
      check_image
      printf "Running tests in container...\n"
      docker run -it idaes/idaes_jupyterhub /bin/bash -c "cd /home/idaes && pytest"
      ;;
    notebook)
      check_image
      printf "Starting Jupyter...\n"
      docker run -p 8888:8888 -it idaes/idaes_jupyterhub
      ;;
    update)
      printf "Updating IDAES image...\n"
      install_image
      ;;
    create)
      printf "Create new Docker image file\n"
      shift
      build_image $*
      ;;
    -h|help)
      usage
      ;;
    *)
      usage
esac
