name: Run pylint
description: Run static analysis using pylint
# TODO add inputs (options) as needed
runs:
  using: "composite"
  steps:
    - name: Install pylint dependencies
      shell: bash
      run: |
        PIP_INSTALL="pip --no-cache-dir install --progress-bar off"
        $PIP_INSTALL --upgrade pip setuptools wheel
        # TODO the pylint version will have to be pinned
        # TODO installing idaes is necessary in our case because we import some idaes code in pylint plugins
        $PIP_INSTALL -r requirements-dev.txt
        # don't think we need to install the extensions, though
    - name: Run pylint (errors only)
      # use custom options for bash since the default causes the step to fail immediately for any non-zero return code of intermediate commands
      shell: bash --noprofile --norc {0}
      run: |
        pylint --rcfile=./.pylint/pylintrc --disable=W,C,R,I --output-format=idaes_reporters.MultiReporter idaes/
        pylint_exit_status=$?

        # render report
        base_url="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/main/$GITHUB_SHA"
        pylint_output_path=pylint.json
        echo "::group::Rendered pylint report"
        python .pylint/render_report.py --base-url="$base_url" "$pylint_output_path"
        echo "::endgroup::"

        exit "$pylint_exit_status"
