name: Set up IDAES
description: Install IDAES and extensions
inputs:
  install-target:
    description: 'Command-line arguments and options to pass to the install command, e.g. pip install'
    required: true
  install-command:
    description: 'Command to use to install `install-target`'
    required: false
    default: pip --no-cache-dir install --progress-bar off
runs:
  using: "composite"
  steps:
    - name: Update pip and other packaging tools
      shell: bash
      run: |
        ${{ inputs.install-command }} pip setuptools wheel
    - name: Install idaes and dependencies
      shell: bash
      run: |
        echo '::group::Output of "pip install" command'
        ${{ inputs.install-command }} ${{ inputs.install-target}}
        echo '::endgroup::'
        echo '::group::Output of "pip show pyomo idaes-pse"'
        pip show pyomo idaes-pse
        echo '::endgroup::'
        # idaes --version
    - name: Install extensions
      shell: bash
      run: |
        echo '::group::Output of "idaes get-extensions" command'
        idaes get-extensions --verbose
        echo '::endgroup::'
