_id: d779730c7cc94155877a24e2e8be2ad1
created: '2023-03-25T08:46:03.559192'
description: Built-in IDAES workspace
htmldocs:
- https://idaes-pse.readthedocs.io/en/stable
- '{dmf_root}/docs/build/html'
modified: '2023-03-25T08:46:03.559192'
name: IDAES
