_id: d779730c7cc94155877a24e2e8be2ad1
created: '2024-03-21T18:10:42.831508'
description: Built-in IDAES workspace
htmldocs:
- https://idaes-pse.readthedocs.io/en/stable
- '{dmf_root}/docs/build/html'
modified: '2024-03-21T18:10:42.831508'
name: IDAES
