#################################################################################
# The Institute for the Design of Advanced Energy Systems Integrated Platform
# Framework (IDAES IP) was produced under the DOE Institute for the
# Design of Advanced Energy Systems (IDAES).
#
# Copyright (c) 2018-2026 by the software owners: The Regents of the
# University of California, through Lawrence Berkeley National Laboratory,
# National Technology & Engineering Solutions of Sandia, LLC, Carnegie Mellon
# University, West Virginia University Research Corporation, et al.
# All rights reserved.  Please see the files COPYRIGHT.md and LICENSE.md
# for full copyright and license information.
#################################################################################
"""
This module contains regression tests for the DiagnosticsToolbox to verify
its behavior with variables that have None values.
"""

from io import StringIO

import pytest

from pyomo.environ import (
    Block,
    ConcreteModel,
    Constraint,
    Var,
)

from idaes.core.util.diagnostics_tools.diagnostics_toolbox import (
    DiagnosticsToolbox,
)

__author__ = "Alex Dowling, Douglas Allan, Andrew Lee"


class TestVariablesWithNoneValue:
    def err_msg(self, j):
        return (
            f"Found {j} variables with a value of None in the mathematical "
            "program generated by the model. They must be initialized with non-None "
            "values before numerical analysis can proceed. Run "
            + DiagnosticsToolbox.display_variables_with_none_value_in_activated_constraints.__name__
            + " to display a list of these variables."
        )

    @pytest.fixture(scope="function")
    def model(self):
        m = ConcreteModel()
        m.u = Var()
        m.w = Var(initialize=1)
        m.x = Var(initialize=1)
        m.y = Var(range(3), initialize=[1, None, 2])
        m.z = Var()

        m.con_w = Constraint(expr=m.w == 0)
        m.con_x = Constraint(expr=m.x == 1)

        def rule_con_y(b, i):
            return b.y[i] == 3

        m.con_y = Constraint(range(3), rule=rule_con_y)
        m.con_z = Constraint(expr=m.x + m.z == -1)

        m.block1 = Block()
        m.block1.a = Var()
        m.block1.b = Var(initialize=7)
        m.block1.c = Var(initialize=-5)
        m.block1.d = Var()

        m.block1.con_a = Constraint(expr=m.block1.a**2 + m.block1.b == 1)
        m.block1.con_b = Constraint(expr=m.block1.b + m.block1.c == 3)
        m.block1.con_c = Constraint(expr=m.block1.c + m.block1.a == -4)
        return m

    @pytest.mark.unit
    def test_verify_active_variables_initialized(self, model):
        diag_tbx = DiagnosticsToolbox(model)
        with pytest.raises(
            RuntimeError,
            match=self.err_msg(3),
        ):
            diag_tbx._verify_active_variables_initialized()

        model.block1.deactivate()
        with pytest.raises(
            RuntimeError,
            match=self.err_msg(2),
        ):
            diag_tbx._verify_active_variables_initialized()

        model.con_y[1].deactivate()
        model.con_z.deactivate()
        # No uninitialized variables in remaining constraints
        diag_tbx._verify_active_variables_initialized()

    @pytest.mark.unit
    def test_error_handling(self, model):
        diag_tbx = DiagnosticsToolbox(model)
        methods = [
            "display_variables_with_extreme_jacobians",
            "display_constraints_with_extreme_jacobians",
            "display_extreme_jacobian_entries",
            "display_near_parallel_constraints",
            "display_near_parallel_variables",
            "display_constraints_with_mismatched_terms",
            "display_constraints_with_canceling_terms",
            "display_constraints_with_no_free_variables",
            "report_numerical_issues",
        ]
        for mthd in methods:
            mthd_obj = getattr(diag_tbx, mthd)
            with pytest.raises(
                RuntimeError,
                match=self.err_msg(3),
            ):
                mthd_obj()

    @pytest.mark.unit
    def test_display_problematic_constraint_terms(self, model):
        """
        This method needs to be split into a separate function
        because it takes a constraint as an argument.
        """
        diag_tbx = DiagnosticsToolbox(model)
        with pytest.raises(
            RuntimeError,
            match=self.err_msg(3),
        ):
            diag_tbx.display_problematic_constraint_terms(model.con_y[1])
        # The current implementation shows an error message whether or not
        # a problematic constraint is called.
        with pytest.raises(
            RuntimeError,
            match=self.err_msg(3),
        ):
            diag_tbx.display_problematic_constraint_terms(model.con_y[0])

    @pytest.mark.unit
    def test_display_variables_with_none_value_in_activated_constraints(self, model):
        diag_tbx = DiagnosticsToolbox(model)
        stream = StringIO()

        diag_tbx.display_variables_with_none_value_in_activated_constraints(
            stream=stream,
        )

        expected = """====================================================================================
The following variable(s) have a value of None:

    y[1]
    z
    block1.a

====================================================================================
"""
        assert stream.getvalue() == expected
