
paths:
  source: src
  output: docs_test
  html: _build/html
notebook:
    num_workers: 1
    continue_on_error: true
    test_mode: true
    timeout: 600
    error_file: notebook-errors.txt
    template: docs/jupyter_notebook_sphinx.tpl
    directories:
      - source: Examples/Advanced/CustomUnitModels
      - source: Examples/Advanced/DataRecon
      - source: Examples/MatOpt
      - source: Examples/SurrMod/ALAMO
      - source: Examples/SurrMod/Helmet
      - source: Examples/SurrMod/PySMO
      - source: Examples/Tools
      - source: Examples/UnitModels
      - source: Tutorials/Advanced/ParamEst
      - source: Tutorials/Basics
notebook_index:
  input_file: notebook_index.yml
  output_file: src/notebook_index.ipynb
sphinx:
    args: "-b html -T docs_test docs_test/_build/html"
    error_file: sphinx-errors.txt
