name: Run pytest
description: Run tests with pytest
inputs:
  extra-args:
    description: Extra CLI arguments to pass to the pytest command (in addition to those specified here)
    required: false
    default: ''
  markexpr:
    description: Mark expression to pass to pylint's -m flag
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Install dependencies needed for running tests
      shell: bash
      run: |
        python -m pip install pytest coverage pytest-cov
    - name: Run pytest
      shell: bash
      run: |
        pytest idaes/ -m '${{ inputs.markexpr }}' ${{ inputs.extra-args }}
