# -*- coding: utf-8 -*-
#################################################################################
# The Institute for the Design of Advanced Energy Systems Integrated Platform
# Framework (IDAES IP) was produced under the DOE Institute for the
# Design of Advanced Energy Systems (IDAES).
#
# Copyright (c) 2018-2026 by the software owners: The Regents of the
# University of California, through Lawrence Berkeley National Laboratory,
# National Technology & Engineering Solutions of Sandia, LLC, Carnegie Mellon
# University, West Virginia University Research Corporation, et al.
# All rights reserved.  Please see the files COPYRIGHT.md and LICENSE.md
# for full copyright and license information.
#################################################################################
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: idaes/core/io/pyomo_model_state.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n%idaes/core/io/pyomo_model_state.proto"V\n\x08Metadata\x12\x16\n\x0e\x66ormat_version\x18\x01 \x01(\t\x12\x0f\n\x07\x63reated\x18\x02 \x01(\x02\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x11\n\tcoauthors\x18\x04 \x03(\t"\xdf\x02\n\x05\x42lock\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x04type\x18\x02 \x01(\x0e\x32\n.BlockType\x12\x0e\n\x06parent\x18\x03 \x01(\x05\x12\x1e\n\nindex_type\x18\x04 \x01(\x0e\x32\n.IndexType\x12\x30\n\x0eindexed_data_f\x18\x05 \x03(\x0b\x32\x18.Block.IndexedDataFEntry\x12\x30\n\x0eindexed_data_s\x18\x06 \x03(\x0b\x32\x18.Block.IndexedDataSEntry\x12\x18\n\x04\x64\x61ta\x18\x07 \x01(\x0b\x32\n.BlockData\x1a?\n\x11IndexedDataFEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.BlockData:\x02\x38\x01\x1a?\n\x11IndexedDataSEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.BlockData:\x02\x38\x01"P\n\tBlockData\x12\r\n\x05value\x18\x01 \x01(\x01\x12\r\n\x05\x66ixed\x18\x02 \x01(\x08\x12\r\n\x05stale\x18\x03 \x01(\x08\x12\n\n\x02lb\x18\x04 \x01(\x01\x12\n\n\x02ub\x18\x05 \x01(\x01"<\n\x05Model\x12\x1b\n\x08metadata\x18\x01 \x01(\x0b\x32\t.Metadata\x12\x16\n\x06\x62locks\x18\x02 \x03(\x0b\x32\x06.Block*B\n\tBlockType\x12\t\n\x05\x42LOCK\x10\x00\x12\x07\n\x03VAR\x10\x01\x12\t\n\x05PARAM\x10\x02\x12\n\n\x06SUFFIX\x10\x03\x12\n\n\x06\x43ONFIG\x10\x04*,\n\tIndexType\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06STRING\x10\x01\x12\t\n\x05\x46LOAT\x10\x02\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "idaes.core.io.pyomo_model_state_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_BLOCK_INDEXEDDATAFENTRY"]._options = None
    _globals["_BLOCK_INDEXEDDATAFENTRY"]._serialized_options = b"8\001"
    _globals["_BLOCK_INDEXEDDATASENTRY"]._options = None
    _globals["_BLOCK_INDEXEDDATASENTRY"]._serialized_options = b"8\001"
    _globals["_BLOCKTYPE"]._serialized_start = 627
    _globals["_BLOCKTYPE"]._serialized_end = 693
    _globals["_INDEXTYPE"]._serialized_start = 695
    _globals["_INDEXTYPE"]._serialized_end = 739
    _globals["_METADATA"]._serialized_start = 41
    _globals["_METADATA"]._serialized_end = 127
    _globals["_BLOCK"]._serialized_start = 130
    _globals["_BLOCK"]._serialized_end = 481
    _globals["_BLOCK_INDEXEDDATAFENTRY"]._serialized_start = 353
    _globals["_BLOCK_INDEXEDDATAFENTRY"]._serialized_end = 416
    _globals["_BLOCK_INDEXEDDATASENTRY"]._serialized_start = 418
    _globals["_BLOCK_INDEXEDDATASENTRY"]._serialized_end = 481
    _globals["_BLOCKDATA"]._serialized_start = 483
    _globals["_BLOCKDATA"]._serialized_end = 563
    _globals["_MODEL"]._serialized_start = 565
    _globals["_MODEL"]._serialized_end = 625
# @@protoc_insertion_point(module_scope)
