# This is a stub that helps people use the Python script to build docs
all default html:
	@echo "The Makefile to build Sphinx docs has been replaced by the 'build.py'"
	@echo "in this directory. To run:"
	@echo "   python build.py"
	@echo "To see help on (very limited) options, use 'python build.py -h'"
