# -*- coding: utf-8 -*-
#
# IDAES documentation build configuration file
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
from collections import namedtuple
import os
import sys

# For importing from idaes.<modules..>
sys.path.insert(0, os.path.abspath(".."))
import idaes.ver
import sphinx_rtd_theme

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.ifconfig",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "sphinx.ext.napoleon",
    "sphinx.ext.autosectionlabel",
    "sphinxarg.ext",
    "sphinx.ext.doctest",
]

# Put type hints in the description, not signature
autodoc_typehints = "description"

# Avoid duplicating heading labels across parallelly constructed documentation
autosectionlabel_prefix_document = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The encoding of source files.
#
# source_encoding = 'utf-8-sig'

# The main toctree document.
main_doc = "index"

# General information about the project.
project = "IDAES"
copyright = "2016-2021, David Miller et al."
author = "The IDAES project"


# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = idaes.ver.__version__
# The full version, including alpha/beta/rc tags.
release = idaes.ver.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#
# today = ''
#
# Else, today_fmt is used as the format for a strftime call.
#
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["apidoc/*tests*"]

# The reST default role (used for this markup: `text`) to use for all
# documents.
#
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# Global constants for supported Python versions
IDAES_PV_MIN, IDAES_PV_MAX, IDAES_PV_DEFAULT = "3.8", "3.11", "3.10"

# This block of text will be virtually present at the end of every file.
# Used here to define substitutions for re-used URLs, e.g. just add "|examples-site|" to
# any page and it will be replaced with the hyperlink and text shown below.

rst_epilog = f"""
.. |python-min| replace:: {IDAES_PV_MIN}
.. |python-max| replace:: {IDAES_PV_MAX}
.. |examples-site| replace:: `examples website`_
.. _examples website: https://idaes-examples.readthedocs.io/en/latest/
.. |github-issues| replace:: `Github issues page`_
.. _Github issues page: https://github.com/IDAES/idaes-pse/issues
"""


class RobustReplacements(dict):
    """These replacements are needed because the Sphinx replacements are
    not expanded within code blocks.
    """

    def __call__(self, app, docname, source):
        text = source[0]
        for to_replace, replace_with in self.items():
            text = text.replace(to_replace, replace_with)
        source[0] = text


_python_versions_replacements = RobustReplacements(
    {
        "|python-min|": IDAES_PV_MIN,
        "|python-max|": IDAES_PV_MAX,
        "|python-default|": IDAES_PV_DEFAULT,
    }
)

# Intersphinx configuration (added 02/22/2024 -Dan G.)
# - To use in doc files, prefix cross-references with ':external:'
# - To explicitly choose an external project prefix with ':external+NAME:',
#   where NAME matches one of the dictionary keys below.
intersphinx_mapping = {
    # Python standard library.
    "python": ("https://docs.python.org/3", None),
    # add links to idaes-ui
    "ui": ("https://idaes-ui.readthedocs.io/en/latest/", None),
    # add links to Pyomo
    "pyomo": ("https://pyomo.readthedocs.io/en/stable/", None),
}

# -- Options for HTML output ----------------------------------------------

html_theme = "sphinx_book_theme"
html_theme_options = {
    "logo": {
        "image_light": "images/idaes-logo-text.png",
        "image_dark": "images/idaes-logo-text.png",
    },
    "repository_provider": "github",
    "repository_url": "https://github.com/idaes/idaes-pse",
    "use_repository_button": True,
    "path_to_docs": "docs",
}
# html_theme = "sphinx_rtd_theme"
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
html_title = "IDAES v{}".format(release)
html_logo = "images/idaes-logo-100x100.png"
html_favicon = "images/idaes-logo.ico"
html_static_path = ["static", "images"]
html_css_files = ["css/custom.css", "css/badge_only.css"]
html_extra_path = ["static/extra/"]
htmlhelp_basename = "IDAESdoc"
html_context = {
    "footer_logos": {
        "row1": [
            {
                "alt": "National Energy Technology Laboratory logo",
                "src": "footer_logo_NETL.png",
                "href": "https://netl.doe.gov/",
            },
            {
                "alt": "Lawrence Berkeley National Laboratory logo",
                "src": "footer_logo_LBNL.jpg",
                "href": "https://www.lbl.gov/",
            },
            {
                "alt": "Sandia National Laboratory logo",
                "src": "footer_logo_Sandia.png",
                "href": "https://www.sandia.gov/",
            },
            {
                "alt": "Department of Energy logo",
                "src": "footer_logo_DOE.jpg",
                "href": "https://www.energy.gov/",
            },
        ],
        "row2": [
            {
                "alt": "Carnegie Mellon University logo",
                "src": "footer_logo_CMU.png",
                "href": "https://www.cmu.edu/",
            },
            {
                "alt": "West Virginia University logo",
                "src": "footer_logo_West_VA_U.png",
                "href": "https://www.wvu.edu/",
            },
            {
                "alt": "University of Notre Dame logo",
                "src": "footer_logo_Notre_Dame.png",
                "href": "https://www.nd.edu/",
            },
            {
                "alt": "Georgia Institute of Technology logo",
                "src": "footer_logo_Georgia_Tech.png",
                "href": "https://www.gatech.edu/",
            },
        ],
    }
}

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    "preamble": r"\usepackage{enumitem}\setlistdepth{99}",
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (main_doc, "IDAES.tex", "IDAES Documentation", "IDAES team", "manual")
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#
# latex_use_parts = False

# If true, show page references after internal links.
#
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
#
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
#
# latex_appendices = []

# It false, will not define \strong, \code, 	itleref, \crossref ... but only
# \sphinxstrong, ..., \sphinxtitleref, ... To help avoid clash with user added
# packages.
#
# latex_keep_old_macro_names = True

# If false, no module index is generated.
#
# latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [("dmf/cli", "dmf", "Data Management Framework", [author], 1)]

# If true, show URL addresses after external links.
#
# man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        main_doc,
        "IDAES",
        "IDAES Documentation",
        author,
        "IDAES",
        "One line description of project.",
        "Miscellaneous",
    )
]

# Documents to append as an appendix to all manuals.
#
# texinfo_appendices = []

# If false, no module index is generated.
#
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#
# texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#
# texinfo_no_detailmenu = False


def setup(app):
    app.connect("source-read", _python_versions_replacements)
