name: PR

on:
  pull_request:
    types:
      # ready_for_review occurs when a PR is opened in non-draft mode,
      # or when a draft PR is turned to non-draft
      - ready_for_review
      # synchronize occurs whenever commits are pushed to the PR branch
      - synchronize

env:
  # default Python version to use for checks that do not require multiple versions
  DEFAULT_PYTHON_VERSION: '3.7'

defaults:
  run:
    shell: bash

jobs:
  pytest:
    name: Tests (py${{ matrix.python-version }}/${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
        os:
          - ubuntu-18.04
          - windows-latest
    steps:
      - name: Display debug info
        run: |
          echo '${{ toJSON(matrix) }}'
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up idaes
        uses: ./.github/actions/setup-idaes
        with:
          install-target: '.'
      - name: Run pytest (not integration)
        uses: ./.github/actions/pytest
        with:
          markexpr: not integration
          extra-args: --cov
      - name: Upload coverage report to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash)
  build-docs:
    name: Build Sphinx docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Set up idaes
        uses: ./.github/actions/setup-idaes
        with:
          install-target: -r requirements-dev.txt
      - name: Build Sphinx docs
        uses: ./.github/actions/build-docs
      - name: Publish built docs
        uses: actions/upload-artifact@v2
        with:
          name: idaes-pse-docs-html
          path: docs/build/html/
          retention-days: 7
  pylint:
    name: pylint (errors only)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Run pylint
        uses: ./.github/actions/pylint
